---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: blue
  template:
    metadata:
      name: java
      labels:
        app: web
        version: blue
    spec:
      containers:
      - name: app
        image: zubairbhat722/my-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 2048Mi  
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: java
  labels:
    app: web
spec:
  selector:
    app: web
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
