---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: jenkins
  labels: java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java
      version: blue
  template:
    metadata:
      name: java
      labels:
        app: web
        version: blue
    spec:
      containers:
      - name: java
        image: zubairbhat722/my-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi  
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: java-deployment
  labels:
    app: java
spec:
  selector:
    app: java
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
